<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>

<div class="add-to-links">


<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <button type="button" class="btn btn-wishlist" title="Wishlist"><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist"><i class="fa fa-heart"></i></a></button>
<?php endif; ?>
<?php
    $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);
?>
<?php if($_compareUrl) : ?>
    <button type="button" class="btn btn-compare" title="Compare"><a href="<?php echo $_compareUrl ?>" class="link-compare"><i class="fa fa-bar-chart-o"></i></a></button>
<?php endif; ?>

    <button type="button" title="<?php echo $buttonTitle ?>" class="btn btn-cart" onclick=""><?php echo $this->__('Contact us for availability') ?></button>
</div>

