<?php

/**
USAGE:

Simple:

<?php echo $this->getLayout()->createBlock('customer/widget_dob')
   ->setDate($this->getCustomer()->getDob())
   ->toHtml() ?>

For checkout/onepage/billing.phtml:

<?php echo $this->getLayout()->createBlock('customer/widget_dob')
   ->setDate($this->getCustomer()->getDob())
   ->setFieldIdFormat('billing:%s')
   ->setFieldNameFormat('billing[%s]')
   ->toHtml() ?>

NOTE: Regarding styles - if we leave it this way, we'll move it to boxes.css
      Alternatively we could calculate widths automatically using block input parameters.
*/

/**
 * @see Mage_Customer_Block_Widget_Dob
 */
?>
<div class="form-group">
    <label for="<?php echo $this->getFieldId('month')?>"  class="<?php if ($this->isRequired()) echo 'required' ?> control-label col-sm-2"><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->__('Date of Birth') ?></label>
    <div class="col-sm-10 input-box customer-dob">
        <?php
        $this->setDateInput('d',
            '<div class="dob-day">
             <input type="text" id="' . $this->getFieldId('day') . '" name="' . $this->getFieldName('day') . '" value="' . $this->getDay() . '" title="' . $this->__('Day') . '" class="form-control input-text validate-custom" ' . $this->getFieldParams() . ' placeholder="DD"/>
             <label for="' . $this->getFieldId('day') . '">' . $this->__('DD') . '</label>
         </div>'
        );

        $this->setDateInput('m',
            '<div class="dob-month">
             <input type="text" id="' . $this->getFieldId('month') . '" name="' . $this->getFieldName('month') . '" value="' . $this->getMonth()  . '" title="' . $this->__('Month')  . '" class="form-control input-text validate-custom" ' . $this->getFieldParams()  . ' placeholder="YY"/>
             <label for="' . $this->getFieldId('month') . '">' . $this->__('MM')  . '</label>
         </div>'
        );

        $this->setDateInput('y',
            '<div class="dob-year">
             <input type="text" id="' . $this->getFieldId('year') . '" name="' . $this->getFieldName('year') . '" value="' . $this->getYear()  . '" title="' . $this->__('Year')  . '" class="form-control input-text validate-custom" ' . $this->getFieldParams()  . ' placeholder="YYYY"/>
             <label for="' . $this->getFieldId('year') . '">' . $this->__('YYYY')  . '</label>
         </div>'
        );
        ?>
        <?php echo $this->getSortedDateInputs() ?>
        <div class="dob-full" style="display:none;">
            <input type="hidden" id="<?php echo $this->getFieldId('dob')?>" name="<?php echo $this->getFieldName('dob')?>" />
        </div>

        <div class="validation-advice" style="display:none;"></div>
    </div>
    <script type="text/javascript">
        //<![CDATA[
        var customer_dob = new Varien.DOB('.customer-dob', <?php echo $this->isRequired() ? 'true' : 'false' ?>, '<?php echo $this->getDateFormat() ?>');
        //]]>
    </script>
</div>
