<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>
<h1 class="main-heading text-center"><?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
        <?php echo $this->__('Login or Create an Account') ?>
    <?php else: ?>
        <?php echo $this->__('Login'); ?>
    <?php endif; ?></h1>

<section class="login-area account-login<?php if (!$this->helper('customer')->isRegistrationAllowed()) echo ' login-only' ?>">
    <div class="row">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <div class="row col2-set">
            <?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
            <div class="col-sm-6 new-users">
                <div class="panel panel-smart content">
                    <div class="panel-heading">
                        <h2><?php echo $this->__('New Here?') ?></h2>
                    </div>
                    <div class="panel-body">
                        <p class="form-instructions"><?php echo $this->__('Registration is free and easy!') ?></p>
                        <ul class="benefits">
                            <li><?php echo $this->__('Faster checkout') ?></li>
                            <li><?php echo $this->__('Save multiple shipping addresses') ?></li>
                            <li><?php echo $this->__('View and track orders and more') ?></li>
                        </ul>
                        <div class="buttons-set">
                            <a title="<?php echo $this->__('Create an Account') ?>" class="button" href="<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>"><span><span><?php echo $this->__('Create an Account') ?></span></span></a>
                        </div>
                    </div>
                </div>

            </div>
            <?php endif; ?>
            <?php // This column should be col-1 if the registration column is not displayed ?>
            <div class="col-sm-6 registered-users row">
                <div class="col-xs-12">
                    <div class="content fieldset panel panel-smart">
                        <div class="panel-heading">
                            <h2><?php echo $this->__('Already registered?') ?></h2>
                        </div>
                        <div class="panel-body">
                            <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form" class="form-inline row" role="form">
                                <?php echo $this->getBlockHtml('formkey'); ?>

                                <div class="col-xs-12">
                                    <p class="form-instructions"><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                                </div>
                                    <div class="form-group col-xs-12 col-md-5">
                                        <label for="email" class="required sr-only"><em>*</em><?php echo $this->__('Email Address') ?></label>
                                        <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-at"></i></span>
                                            <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email form-control" title="<?php echo $this->__('Email Address') ?>" />
                                        </div>
                                    </div>
                                    <div class="form-group col-xs-12 col-md-5">
                                        <label for="pass" class="required sr-only"><em>*</em><?php echo $this->__('Password') ?></label>
                                        <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                                            <input type="password" name="login[password]" class="input-text required-entry validate-password form-control" id="pass" title="<?php echo $this->__('Password') ?>" />
                                        </div>
                                    </div>
                                    <div class="form-group col-xs-12 col-md-2">
                                        <button type="submit" class="button btn btn-black" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><?php echo $this->__('Login') ?></button>
                                    </div>
                                    <div class="form-group col-xs-12">
                                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                                    </div>
                                    <div class="form-group col-xs-12">
                                        <?php //echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                                    </div>

                            </form>
                        </div>
                        <script type="text/javascript">
                            //<![CDATA[
                            var dataForm = new VarienForm('login-form', true);
                            //]]>
                        </script>
                    </div>
                </div>
                <div class="col-xs-12">
                <div class="content fieldset panel panel-smart">
                    <div class="panel-heading">
                        <h2><?php echo $this->__('Forgot Your Password?') ?></h2>
                    </div>
                    <div class="panel-body">
                        <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="forgotpassword-form" class="form-horizontal" role="form">
                            <?php echo $this->getBlockHtml('formkey'); ?>

                            <div class="form-group">
                                <div class="col-xs-12">
                                    <label class="sr-only"><?php echo $this->__('Instructions') ?></label>
                                    <p class="form-control-static"><?php echo $this->__('No problem! Provide us your e-mail address and we will send you an email to reset your password') ?><</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class=" col-xs-12 col-sm-10">
                                    <label for="email" class="required sr-only"><em>*</em><?php echo $this->__('Email Address') ?></label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-at"></i></span>
                                        <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email form-control input-large" title="<?php echo $this->__('Email Address') ?>" />
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class=" col-xs-12 col-sm-2">
                                    <button type="submit" class="button btn btn-black" title="<?php echo $this->__('Submit') ?>" name="send" id="send2"><?php echo $this->__('Submit') ?></button>
                                </div>
                            </div>
                        </form>
                        <script type="text/javascript">
                            //<![CDATA[
                            var forgotPasswordForm = new VarienForm('forgotpassword-form', false);
                            //]]>
                        </script>
                    </div>
                </div>
            </div>
            </div>

        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>

    </div>
</section>
