<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>
<h1 class="main-heading text-center"><?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
        <?php echo $this->__('Login or Create an Account') ?>
    <?php else: ?>
        <?php echo $this->__('Login'); ?>
    <?php endif; ?></h1>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<div class="row">
    <div class="col-xs-12">
        <?php echo $this->getChildHtml('customer.login.form.top'); ?>
    </div>
    <div class="col-xs-12 col-sm-6">
<!--        <div class="row">-->
<!--            <div class="col-xs-12">-->
<!--                <div class="row">-->
                    <?php echo $this->getChildHtml('customer.login.form.col.left'); ?>
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
    </div>
    <div class="col-xs-12 col-sm-6">
<!--        <div class="row">-->
<!--            <div class="col-xs-12">-->
<!--                <div class="row">-->
                    <?php echo $this->getChildHtml('customer.login.form.col.right'); ?>
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
    </div>
    <div class="col-xs-12">
        <?php echo $this->getChildHtml('customer.login.form.bottom'); ?>
    </div>
</div>



<section class="row login-area account-login<?php if (!$this->helper('customer')->isRegistrationAllowed()) echo ' login-only' ?>">
            <?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
            <div class="col-sm-6 new-users">

            </div>
            <?php endif; ?>
            <?php // This column should be col-1 if the registration column is not displayed ?>
            <div class="col-sm-6 registered-users">
                <div class="row">

                </div>
            </div>

        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>

</section>
