<?php
$_product = $this->getProduct();
?>
<div class="panel panel-smart">
    <div class="panel-heading page-title">
        <h2 class="panel-title"><?php echo $this->__('Chosen Product'); ?></h2>
    </div>
    <div class="panel-body">
        <div class="">
            <?php // Product Image ?>
            <div class="">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php /* Based on the native RWD styling, product images are displayed at a max of ~400px wide when viewed on a
                            one column page layout with four product columns from a 1280px viewport. For bandwidth reasons,
                            we are going to serve a 300px image, as it will look fine at 400px and most of the times, the image
                            will be displayed at a smaller size (eg, if two column are being used or viewport is smaller than 1280px).
                            This $_imgSize value could even be decreased further, based on the page layout
                            (one column, two column, three column) and number of product columns. */ ?>
                    <?php $_imgSize = 300; ?>
                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize, 200); ?>"
                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="img-responsive"/>
                </a>
            </div>
        </div>

        <div class="">
            <div class="">
                <div class="product-primary">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h4 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name'); ?></a></h4>
                    <?php if($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                </div>
                <div class="description">
                    <?php echo $_product->getShortDescription(); ?>
                </div>
            </div>
        </div>
        <div class="">
            <div class="">
                <?php echo $this->getPriceHtml($_product, true) ?>
            </div>
        </div>
    </div>
</div>