<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */

$cssModes = ['list' => 'fa fa-th-list', 'grid' => 'fa fa-th'];
?>
<?php if($this->getCollection()->getSize()): ?>
<div class="row toolbar">
    <?php if( $this->isExpanded() ): ?>
        <?php if( $this->isEnabledViewSwitcher() ): ?>
            <div class="sorter col-md-2">
                <p class="view-mode display">
                    <?php $_modes = $this->getModes(); ?>
                    <?php if($_modes && count($_modes)>1): ?>
                        <?php foreach ($this->getModes() as $_code=>$_label): ?>
                            <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?> <?php echo (($this->isModeActive($_code))? 'active': '')?>">
                                <i class="<?php echo $cssModes[$_code]; ?>" title="<?php echo $_label ?>"></i></a>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </p>
            </div>
            <?php endif; ?>

            <div class="col-md-2 text-right sort-by-label">
                <label class="control-label"><?php echo $this->__('Sort By') ?></label>
            </div>
            <div class="col-md-3 text-right sort-by">
                <div class="row">
                    <div class="col-md-9 text-left sort-by-select">
                        <select onchange="setLocation(this.value)" title="<?php echo $this->__('Sort By') ?>" class="form-control">
                            <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                                <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                                    <?php echo $this->__($_order) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="col-md-3 text-right sort-by-direction display">
                        <?php if($this->getCurrentDirection() == 'desc'): ?>
                            <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" class="sort-by-switcher sort-by-switcher--desc" title="<?php echo $this->__('Set Ascending Direction') ?>"><i class="fa fa-caret-square-o-up" title="asc"></i></a>
                        <?php else: ?>
                            <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" class="sort-by-switcher sort-by-switcher--asc" title="<?php echo $this->__('Set Descending Direction') ?>"><i class="fa fa-caret-square-o-down" title="desc"></i></a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>

    <?php endif; ?>
    <div class="col-md-3 text-right limiter-label">
        <?php if($this->getLastPageNum()>1): ?>
            <label class="control-label amount amount--has-pages">
                <?php echo $this->__('%s-%s of %s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
            </label>
        <?php else: ?>
            <label class="control-label amount amount--no-pages">
                <?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?>
            </label>
        <?php endif; ?>
    </div>
    <div class="col-md-2 text-right limiter">
            <div class="limiter">
                <select onchange="setLocation(this.value)" title="<?php echo $this->__('Results per page'); ?>" class="form-control">
                <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                    <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                        <?php echo $_limit ?>
                    </option>
                <?php endforeach; ?>
                </select>
            </div>

        <?php echo $this->getPagerHtml() ?>

    </div>
</div>
</div>
<?php endif ?>
