<?php
/** @var Mage_Page_Block_Html_Topmenu_Renderer $this */
/** @var Varien_Data_Tree_Node $menuTree */
/** @var string $childrenWrapClass */

$html = '';

$children = $menuTree->getChildren();
$parentLevel = $menuTree->getLevel();
$childLevel = is_null($parentLevel) ? 0 : $parentLevel + 1;

$counter = 1;
$childrenCount = $children->count();

$parentPositionClass = $menuTree->getPositionClass();
$itemPositionClassPrefix = $parentPositionClass ? $parentPositionClass . '-' : 'nav-';

foreach ($children as $child) {
    $topLink = '';

    $child->setLevel($childLevel);
    $child->setIsFirst($counter == 1);
    $child->setIsLast($counter == $childrenCount);
    $child->setPositionClass($itemPositionClassPrefix . $counter);


    $outermostClassCode = 'level'. $childLevel;
    $_hasChildren = ($child->hasChildren()) ? 'has-children' : '';


    if ( !$child->hasChildren() ) {
        $html .= '<li '. $this->_getRenderedMenuItemAttributes($child) .'>';
        $html .= '<a href="'. $child->getUrl() .'" class="'. $outermostClassCode .' '. $_hasChildren .'" tabindex="-1">'. $this->escapeHtml($this->__($child->getName())) .'</a></li>';
        continue;
    }
    $child->setClass('dropdown');
    $html .= '<li '. $this->_getRenderedMenuItemAttributes($child) .'>';


    $topLink = '';

    $html .= '<a href="'. $child->getUrl() .'" class="'. $outermostClassCode .' '. $_hasChildren .' dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="10">'. $this->escapeHtml($this->__($child->getName())) .'</a>';

    if (!empty($childrenWrapClass)) {
        $html .= '<div class="'. $childrenWrapClass .'">';
    }

    $nextChildLevel = $childLevel + 1;

    if (!empty($_hasChildren)) {
        $html .= '<ul class="level'. $childLevel .' dropdown-menu" role="menu">';
        $html .= '<li class="level'. $nextChildLevel .'">';
        $html .= '<a href="'. $child->getUrl() .'" class="'. $outermostClassCode .' '. $_hasChildren .'"">'. $this->escapeHtml($this->__($child->getName())) .'</a>';
        $html .= '</li>';

//        $html .=     '<li class="level'. $nextChildLevel .'">';
//        $html .=         '<a  tabindex="-1" class="level'. $nextChildLevel .'" href="'. $child->getUrl() .'">';
//        $html .=             $this->__('View All ') . $this->escapeHtml($this->__($child->getName()));
//        $html .=         '</a>';
//        $html .=     '</li>';
        $html .=     $this->render($child, $childrenWrapClass);
        $html .= '</ul>';
    }

    if (!empty($childrenWrapClass)) {
        $html .= '</div>';
    }

    $html .= '</li>';

    $counter++;
}

return $html;
