<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
/* @var $this Mage_Catalog_Block_Product_List */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="product-filter category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <div class="row products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <div class="col-xs-12 item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <div class="product-col list clearfix">
                <?php // Product Image ?>
                <div class="image">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                        <?php /* Based on the native RWD styling, product images are displayed at a max of ~400px wide when viewed on a
                            one column page layout with four product columns from a 1280px viewport. For bandwidth reasons,
                            we are going to serve a 300px image, as it will look fine at 400px and most of the times, the image
                            will be displayed at a smaller size (eg, if two column are being used or viewport is smaller than 1280px).
                            This $_imgSize value could even be decreased further, based on the page layout
                            (one column, two column, three column) and number of product columns. */ ?>
                        <?php $_imgSize = 300; ?>
                        <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                             src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                             alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="img-responsive"/>
                    </a>
                </div>


                <?php // Product description ?>
                <div class="product-shop caption">
                    <div class="f-fix">
                        <div class="product-primary">
                            <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                            <h4 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h4>
                            <?php if($_product->getRatingSummary()): ?>
                            <?php echo $this->getReviewsSummaryHtml($_product) ?>
                            <?php endif; ?>

                            <?php
                                $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                foreach($_nameAfterChildren as $_nameAfterChildName):
                                    $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                    $_nameAfterChild->setProduct($_product);
                            ?>
                                <?php echo $_nameAfterChild->toHtml(); ?>
                            <?php endforeach; ?>
                        </div>
                        <div class="description co">
                            <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                        </div>
                        <div class="product-secondary">
                            <?php echo $this->getPriceHtml($_product, true) ?>
                        </div>
                        <div class="product-secondary">
                            <a title="<?php echo $this->__('View Details') ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                        </div>
                        <div class="product-secondary">
                            <div class="cart-button button-group add-to-links">
                                <?php if($_product->isSaleable() && !$_product->canConfigure()): ?>
                                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart btn btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to Cart') ?> <i class="fa fa-shopping-cart"></i></button>
                                <?php elseif($_product->isSaleable()): ?>

                                <?php else: ?>
                                    <p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>

                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <button type="button" class="btn btn-wishlist" title="Wishlist"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><i class="fa fa-heart"></i></a></button>
                                <?php endif; ?>
                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                    <button type="button" class="btn btn-compare" title="Compare"><a href="<?php echo $_compareUrl ?>" class="link-compare"><i class="fa fa-bar-chart-o"></i></a></button>
                                <?php endif; ?>
                                <button type="button" title="<?php echo $this->__('Contact us for availability') ?>" class="btn btn-cart" onclick=""><?php echo $this->__('Contact us for availability') ?></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
    </div>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <div class="row products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
        <?php $_iterator = 0; ?>
        <?php $i=0; foreach ($_productCollection as $_product): ?>
            <div class="col-md-4 col-sm-6 item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                <div class="product-col list clearfix">
                    <div class="">
                        <?php // Product Image ?>
                        <div class="">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                <?php /* Based on the native RWD styling, product images are displayed at a max of ~400px wide when viewed on a
                            one column page layout with four product columns from a 1280px viewport. For bandwidth reasons,
                            we are going to serve a 300px image, as it will look fine at 400px and most of the times, the image
                            will be displayed at a smaller size (eg, if two column are being used or viewport is smaller than 1280px).
                            This $_imgSize value could even be decreased further, based on the page layout
                            (one column, two column, three column) and number of product columns. */ ?>
                                <?php $_imgSize = 300; ?>
                                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="img-responsive"/>
                            </a>
                        </div>
                    </div>

                    <div class="">
                        <div class="">
                            <div class="product-primary">
                                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                <h4 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h4>
                                <?php if($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                <?php endif; ?>

                                <?php
                                $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                foreach($_nameAfterChildren as $_nameAfterChildName):
                                    $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                    $_nameAfterChild->setProduct($_product);
                                    ?>
                                    <?php echo $_nameAfterChild->toHtml(); ?>
                                <?php endforeach; ?>
                            </div>
                            <div class="description">
                                <?php echo Mage::helper('core/string')->truncate($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'), 50); ?>
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                            </div>
                        </div>
                    </div>
                    <div class="">
                        <div class="">
                                <?php echo $this->getPriceHtml($_product, true) ?>
                        </div>
                    </div>
                    <div class="">
                        <a title="<?php echo $this->__('View Details') ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                    </div>
                    <div class="cart-button button-group add-to-links">
                        <div class="">
                            <?php if($_product->isSaleable() && !$_product->canConfigure()): ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart btn btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Book') ?> <i class="fa fa-shopping-cart"></i></button>
                            <?php elseif($_product->isSaleable()): ?>

                            <?php else: ?>
                                <p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                        </div>
                        <div class="">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <button type="button" class="btn btn-wishlist" title="Wishlist"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><i class="fa fa-heart"></i></a></button>
                            <?php endif; ?>


                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <button type="button" class="btn btn-compare" title="Compare"><a href="<?php echo $_compareUrl ?>" class="link-compare"><i class="fa fa-bar-chart-o"></i></a></button>
                            <?php endif; ?>
                        </div>
                        <div class="button-group">
                            <button type="button" title="<?php echo $this->__('Contact us for availability') ?>" class="btn btn-block btn-cart" onclick=""><?php echo $this->__('Contact us for availability') ?></button>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach ?>
    </div>
    <?php endif; ?>
    <div class="clearfix"></div>
    <div class="product-filter toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>

<?php
    //set product collection on after blocks
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach($_afterChildren as $_afterChildName):
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        $_afterChild->setProductCollection($_productCollection);
    ?>
    <?php echo $_afterChild->toHtml(); ?>
<?php endforeach; ?>
