<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="row product-info full">
    <div class="col-sm-4 images-block">
        <?php echo $this->getChildHtml('media') ?>

    </div>
    <div class="col-sm-8 product-details">
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?> class="form-horizontal">
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>

            <div class="panel-smart">
            <div class="product-name">
                <h2><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h2>
            </div>
            <hr />

<!--            Main product attributes to show for the customer-->
            <ul class="list-unstyled manufacturer">
                <li>
                    <span><?php echo $this->__('Sku');?>:</span> <?php echo $_product->getSku(); ?>
                </li>
            </ul>
            <hr />

<!--            Short description SEO!-->
            <?php if ($_product->getShortDescription()):?>
                <div class="short-description">
                    <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                </div>
            <?php endif;?>

            <hr />

            <div class="price">
                <span class="price-head"><?php echo $this->__('Price:'); ?></span>
                <?php echo $this->getPriceHtml($_product); ?>
                <?php echo $this->getChildHtml('bundle_prices') ?>
                <?php echo $this->getTierPriceHtml() ?>
            </div>

            <hr />
            <?php echo $this->getChildHtml('sharing') ?>
            <?php echo $this->getChildHtml('other');?>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <hr />
                <?php //echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            <?php endif;?>

        </form>
    </div>
</div>
    <script type="text/javascript">
        //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                    form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
        //]]>
    </script>
</div>

<div class="tabs-panel panel-smart">
    <!-- Nav Tabs Starts -->
    <ul class="nav nav-tabs" role="tablist">
        <li class="tab-head active">
            <a href="#tab-description"><?php echo $this->__('Description'); ?></a>
        </li>
        <li class="tab-head ">
            <a href="#tab-specification"><?php echo $this->__('Specification'); ?></a>
        </li>
        <li class="tab-head "><a href="#tab-ainfo"><?php echo $this->__('Additional Information'); ?></a></li>
        <?php if ( Mage::getStoreConfigFlag('theam_review/advanced/is_frontend_enabled') ) : ?>
        <li class="tab-head "><a href="#tab-review"><?php echo $this->__('Review'); ?></a></li>
        <?php endif; ?>
    </ul>
    <!-- Nav Tabs Ends -->
    <!-- Tab Content Starts -->
    <div class="tab-content clearfix">
        <!-- Description Starts -->
        <div class="tab-pane active" id="tab-description">
            <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'description') ?></div>
        </div>
        <!-- Description Ends -->
        <!-- Specification Starts -->
        <div class="tab-pane" id="tab-specification">
            <?php echo $this->getChildHtml('additional') ?>
        </div>
        <!-- Specification Ends -->
        <!-- Additional Information Starts -->
        <div class="tab-pane" id="tab-ainfo">
            <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
            </p>
        </div>
        <!-- Additional Information Ends -->
        <?php if ( Mage::getStoreConfigFlag('theam_review/advanced/is_frontend_enabled') ) : ?>
        <!-- Review Starts -->
        <div class="tab-pane" id="tab-review">
            <?php echo $this->getChildHtml('review_form'); ?>
        </div>
        <!-- Review Ends -->
        <?php endif; ?>
    </div>
    <!-- Tab Content Ends -->
</div>