<div class="footer-container" id="footer-group">
    <div class="widget-area footer">
        <div class="container">
            <div class="row">
                <?php echo $this->getChildHtml() ?>
            </div>
        </div>
        <div class="container">
        <div class="row">
            <address class="copyright"><?php echo $this->getCopyright() ?></address>
        </div>
    </div>
    </div>
</div>
