<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<header id="masthead" class="site-header page-header" role="banner">
    <div class="page-header-container container">
        <div class="row">
            <div class="site-branding col-lg-4">.
                <h1 class="site-title">
                <a class="logo" href="<?php echo $this->getUrl('') ?>">THÉAM BVBA
<!--                    <img src="--><?php //echo $this->getLogoSrc() ?><!--" alt="--><?php //echo $this->getLogoAlt() ?><!--" class="large" />-->
                </a>
                </h1>
                <h2 class="site-tagline"><?php echo $this->getLogoAlt() ?></h2>
            </div>
            <!-- Navigation -->

            <div id="header-nav" class="col-lg-8 skip-content">
                <?php echo $this->getChildHtml('topMenu') ?>
            </div>


        </div>
    </div>
    <!-- Search -->

    <!--div id="header-search" class="skip-content">
        <?php echo $this->getChildHtml('topSearch') ?>
    </div-->
</header>


<?php echo $this->getChildHtml('topContainer'); ?>
