<footer id="footer-area">
    <div class="footer-links">
        <div class="container">
            <?php echo $this->getChildHtml() ?>
        </div>
    </div>
    <div class="copyright">
        <div class="container">
            <p class="pull-left"><span class="copyright"><?php echo $this->getCopyright() ?></span></p>
        </div>
        <!-- Payment Gateway Links Starts -->
        <!--ul class="pull-right list-inline">
            <li>
                <img src="images/payment-icon/cirrus.png" alt="PaymentGateway" />
            </li>
            <li>
                <img src="images/payment-icon/paypal.png" alt="PaymentGateway" />
            </li>
            <li>
                <img src="images/payment-icon/visa.png" alt="PaymentGateway" />
            </li>
            <li>
                <img src="images/payment-icon/mastercard.png" alt="PaymentGateway" />
            </li>
            <li>
                <img src="images/payment-icon/americanexpress.png" alt="PaymentGateway" />
            </li>
        </ul-->
        <!-- Payment Gateway Links Ends -->
    </div>
</footer>