<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<header id="header-area">
    <!-- Header Top Starts -->
    <div class="header-top">
        <div class="container">
            <div class="row">
                <!-- Currency & Languages Starts -->
                <div class="col-sm-4 col-xs-12">
                    <div class="pull-left">
                        <!-- Currency Starts -->
                        <div class="btn-group"><?php echo $this->getChildHtml('currency_switcher') ?></div>
                        <!-- Currency Ends -->
                        <!-- Languages Starts -->
                        <div class="btn-group"><?php echo $this->getChildHtml('store_language') ?></div>
                        <div class="btn-group"><p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getAdditionalHtml() ?></p></div>
                        <!-- Languages Ends -->
                    </div>
                </div>
                <!-- Currency & Languages Ends -->
                <!-- Header Links Starts -->
                <div class="col-sm-8 col-xs-12">
                    <div class="header-links">
                        <ul class="nav navbar-nav pull-right">
                            <li class="home show">
                                <a href="<?php echo $this->getUrl('') ?>">
                                    <i class="fa fa-home hidden-lg hidden-md" title="<?php echo $this->__('Home'); ?>"></i>
										<span class="hidden-sm hidden-xs"><?php echo $this->__('Home'); ?></span>
                                </a>
                            </li>
                            <li class="wishlist hidden">
                                <a href="<?php echo $this->getUrl('customer/account/wishlist') ?>">
                                    <i class="fa fa-heart hidden-lg hidden-md" title="<?php echo $this->__('Wish List (%s)', 0); ?>"></i>
										<span class="hidden-sm hidden-xs"><?php echo $this->__('Wish List (<span class="cnt" data-cnt="0">%s</span>)', 0); ?></span>
                                </a>
                            </li>
                            <li class="customer-account hidden">
                                <a href="<?php echo $this->getUrl('customer/account') ?>">
                                    <i class="fa fa-user hidden-lg hidden-md" title="<?php echo $this->__('My Account'); ?>"></i>
										<span class="hidden-sm hidden-xs"><?php echo $this->__('My Account'); ?></span>
                                </a>
                            </li>
                            <!--li class="cart-index">
                                <a href="<?php echo $this->getUrl('') ?>">
                                    <i class="fa fa-shopping-cart hidden-lg hidden-md" title="<?php echo $this->__('Shopping Cart'); ?>"></i>
										<span class="hidden-sm hidden-xs"><?php echo $this->__('Shopping Cart'); ?></span>
                                </a>
                            </li>
                            <li class="checkout">
                                <a href="<?php echo $this->getUrl('') ?>">
                                    <i class="fa fa-crosshairs hidden-lg hidden-md" title="<?php echo $this->__('Checkout'); ?>"></i>
										<span class="hidden-sm hidden-xs"><?php echo $this->__('Checkout'); ?></span>
                                </a>
                            </li-->
                            <li class="customer-account-register show">
                                <a href="<?php echo $this->getUrl('customer/account/register') ?>">
                                    <i class="fa fa-unlock hidden-lg hidden-md" title="<?php echo $this->__('Register'); ?>"></i>
										<span class="hidden-sm hidden-xs"><?php echo $this->__('Register'); ?></span>
                                </a>
                            </li>
                            <li class="customer-account-login show">
                                <a href="<?php echo $this->getUrl('customer/account/login') ?>">
                                    <i class="fa fa-lock hidden-lg hidden-md" title="<?php echo $this->__('Login'); ?>"></i>
										<span class="hidden-sm hidden-xs"><?php echo $this->__('Login'); ?></span>
                                </a>
                            </li>
                            <li class="customer-account-loggedin hidden">
                                <a href="<?php echo $this->getUrl('customer/account/logout') ?>">
                                    <i class="fa fa-lock hidden-lg hidden-md" title="<?php echo $this->__('logout'); ?>"></i>
										<span class="hidden-sm hidden-xs"><?php echo $this->__('logout'); ?></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- Header Links Ends -->
            </div>
        </div>
    </div>
    <!-- Header Top Ends -->
    <!-- Main Header Starts -->
    <div class="main-header">
        <div class="container">
            <div class="row">
                <!-- Logo Starts -->
                <div class="col-sm-6">
                    <div id="logo">
                        <?php if ($this->getIsHomePage()):?>
<h1><a href="<?php echo $this->getUrl('') ?>"><img src="<?php echo $this->getLogoSrc() ?>" title="<?php echo $this->getLogoAlt() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="img-responsive" /></a></h1>
                        <?php else: ?>
<a href="<?php echo $this->getUrl('') ?>"><img src="<?php echo $this->getLogoSrc() ?>" title="<?php echo $this->getLogoAlt() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="img-responsive" /></a>
                        <?php endif; ?>

                    </div>
                </div>
                <!-- Logo Starts -->
                <!-- Shopping Cart Starts -->
                <div class="col-sm-3 hidden">
                    <div id="cart" class="btn-group btn-block">
                        <button type="button" data-toggle="dropdown" class="btn btn-block btn-lg dropdown-toggle">
                            <i class="fa fa-shopping-cart"></i>
                            <span id="cart-total">0</span>
                        </button>
                        <?php echo $this->getChildHtml('minicart_head'); ?>
                    </div>
                </div>
                <!-- Shopping Cart Ends -->
                <!-- Search Starts -->
                <div class="col-xs-12 col-sm-6">
                    <?php echo $this->getChildHtml('topSearch') ?>

                </div>
                <!-- Search Ends -->
            </div>
        </div>
    </div>
   <?php echo $this->getChildHtml('topMenu') ?>




<?php /*
<div class="header-language-background">
    <div class="header-language-container">
        <div class="store-language-container">
            <?php echo $this->getChildHtml('store_language') ?>
        </div>

        <?php echo $this->getChildHtml('currency_switcher') ?>

        <p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getAdditionalHtml() ?></p>
    </div>
</div>

<header id="header" class="page-header">
    <div class="page-header-container">
        <a class="logo" href="<?php echo $this->getUrl('') ?>">
            <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="large" />
            <img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="small" />
        </a>

        <?php // In order for the language switcher to display next to logo on smaller viewports, it will be moved here.
              // See app.js for details ?>
        <div class="store-language-container"></div>

        <!-- Skip Links -->

        <div class="skip-links">
            <a href="#header-nav" class="skip-link skip-nav">
                <span class="icon"></span>
                <span class="label"><?php echo $this->__('Menu'); ?></span>
            </a>

            <a href="#header-search" class="skip-link skip-search">
                <span class="icon"></span>
                <span class="label"><?php echo $this->__('Search'); ?></span>
            </a>

            <a href="#header-account" class="skip-link skip-account">
                <span class="icon"></span>
                <span class="label"><?php echo $this->__('Account'); ?></span>
            </a>

            <!-- Cart -->

            <div class="header-minicart">
                <?php echo $this->getChildHtml('minicart_head'); ?>
            </div>


        </div>

        <!-- Navigation -->

        <div id="header-nav" class="skip-content">
            <?php echo $this->getChildHtml('topMenu') ?>
        </div>

        <!-- Search -->

        <div id="header-search" class="skip-content">
            <?php echo $this->getChildHtml('topSearch') ?>
        </div>

        <!-- Account -->

        <div id="header-account" class="skip-content">
            <?php echo $this->getChildHtml('topLinks') ?>
        </div>

        <!-- Cart -->

        <!-- <div id="header-cart" class="skip-content">
            <div class="mini-cart">
                <div class="menu-wrapper">
                    <div class="menu cart-menu">
                        <div class="empty">Your cart is empty.</div>
                    </div>
                </div>
            </div>
        </div> -->
    </div>
</header>


<?php echo $this->getChildHtml('topContainer'); ?>
*/ ?>

<?php echo $this->getChildHtml('topContainer'); ?>
