<?php
/**
 * Language switcher template
 *
 * @see Mage_Page_Block_Switch
 */
?>
<?php if(count($this->getStores())>1): ?>
    <button class="btn btn-link dropdown-toggle" data-toggle="dropdown">
        <span><?php echo $this->__('Your Language:') ?></span>
        <i class="fa fa-caret-down"></i>
    </button>
    <ul class="pull-left dropdown-menu">
        <li><?php echo $this->__('Your Language') ?></li>
        <?php foreach ($this->getStores() as $_lang): ?>
            <li>
                <a tabindex="-1" href="<?php echo $_lang->getCurrentUrl() ?>" alt="<?php echo $this->escapeHtml($_lang->getName()) ?>"><?php echo $this->escapeHtml($_lang->getName()) ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
