<?php
/**
 * Store switcher template
 *
 * @see Mage_Core_Block_Store_Switcher
 */
?>
<?php if(count($this->getGroups())>1): ?>
    <button class="btn btn-link dropdown-toggle" data-toggle="dropdown">
        <span><?php echo $this->__('Select Store:') ?><</span>
        <i class="fa fa-caret-down"></i>
    </button>
    <ul class="pull-left dropdown-menu">
        <?php foreach ($this->getGroups() as $_group): ?>
            <?php $_selected = ($_group->getId()==$this->getCurrentGroupId()) ? ' store-selection"' : '' ?>
            <li><a tabindex="-1" href="<?php echo $_group->getHomeUrl() ?>" class="<?php echo $_selected ?>"><?php echo $this->escapeHtml($_group->getName()) ?>&nbsp; </a></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
