<?php
?>

<?php /* @var $this Theam_Base_Block_Product_View_Options_Type_Select */ ?>
<?php $_option = $this->getOption() ?>
<div class="form-group">
    <label class="col-sm-3 control-label <?php if ($_option->getIsRequire()) echo 'required' ?>"><?php if ($_option->getIsRequire()) echo '<em>*</em>' ?><?php echo  $this->escapeHtml($_option->getTitle()) ?></label>
    <div class="col-sm-9">
        <?php echo $this->getValuesHtml() ?>
        <?php if ($_option->getIsRequire()): ?>
            <?php if ($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_RADIO || $_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_CHECKBOX): ?>
                <span id="options-<?php echo $_option->getId() ?>-container"></span>
            <?php endif; ?>
        <?php endif;?>
    </div>
</div>

