<div class="col-xs-12 content fieldset panel panel-smart forgotpassword">
    <div class="panel-heading">
        <h2><?php echo $this->__('Forgot Your Password?') ?></h2>
    </div>
    <div class="panel-body">
        <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="forgotpassword-form" class="form-horizontal" role="form">
            <?php echo $this->getBlockHtml('formkey'); ?>

            <div class="form-group col-xs-12">
                <label class="sr-only"><?php echo $this->__('Instructions') ?></label>
                <p><?php echo $this->__('No problem! Provide us your e-mail address and we will send you an email to reset your password') ?></p>
            </div>
            <div class="form-group">
                <div class=" col-xs-12 col-sm-10">
                    <label for="email" class="required sr-only"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-at"></i></span>
                        <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email form-control input-large" title="<?php echo $this->__('Email Address') ?>" />
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class=" col-xs-12 col-sm-2">
                    <button type="submit" class="button btn btn-black" title="<?php echo $this->__('Submit') ?>" name="send" id="send2"><?php echo $this->__('Submit') ?></button>
                </div>
            </div>
        </form>
        <script type="text/javascript">
            //<![CDATA[
            var forgotPasswordForm = new VarienForm('forgotpassword-form', false);
            //]]>
        </script>
    </div>
</div>
