<div class="col-xs-12 panel panel-smart content new-user">
    <div class="panel-heading">
        <h2><?php echo $this->__('New Here?') ?></h2>
    </div>
    <div class="panel-body">
        <div class="form-control-static">
            <p class="form-instructions"><?php echo $this->__('Registration is free and easy!') ?></p>
            <ul class="benefits">
                <li><?php echo $this->__('Faster checkout') ?></li>
                <li><?php echo $this->__('Save multiple shipping addresses') ?></li>
                <li><?php echo $this->__('View and track orders and more') ?></li>
            </ul>
        </div>
        <div class="buttons-set">
            <a title="<?php echo $this->__('Create an Account') ?>" class="button" href="<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>"><span><span><?php echo $this->__('Create an Account') ?></span></span></a>
        </div>
    </div>
</div>