<?php
/**
 * Currency switcher
 *
 * @see Mage_Directory_Block_Currency
 */
?>
<?php if($this->getCurrencyCount()>1): ?>
    <button class="btn btn-link dropdown-toggle" data-toggle="dropdown">
        <span><?php echo $this->__('Your Currency:') ?></span>
        <i class="fa fa-caret-down"></i>
    </button>
    <ul class="pull-left dropdown-menu">
        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
        <li><a tabindex="-1" href="<?php echo $this->getSwitchCurrencyUrl($_code) ?>"><?php echo $_name ?> - <?php echo $_code ?> </a></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
