<div class="page-title">
    <h1 class="main-heading text-center"><?php echo $this->__('Forgot Your Password?') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <div class="col-xs-12">
    <div class="content fieldset panel panel-smart">
        <div class="panel-heading">
            <h2><?php echo $this->__('Retrieve your password here') ?></h2>
        </div>
        <div class="panel-body">
            <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate" class="form-horizontal" role="form">

                <div class="form-group">
                    <div class="col-xs-12">
                        <label class="sr-only"><?php echo $this->__('Instructions') ?></label>
                        <p class="form-control-static"><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-xs-12 col-md-6">
                    <label for="email" class="required sr-only"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-at"></i></span>
                        <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" id="email" alt="email" class="input-text required-entry validate-email form-control input-large" title="<?php echo $this->__('Email Address') ?>" />
                    </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-xs-12">
                    <div class="input-group">
                        <button type="submit" class="button btn btn-black" title="<?php echo $this->__('Submit') ?>" name="send" id="send2"><?php echo $this->__('Submit') ?></button>
                    </div>
                    </div>
                </div>
                <div class="col-xs-12">
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                </div>

            </form>
            </div>
            <script type="text/javascript">
                //<![CDATA[
                var dataForm = new VarienForm('form-validate', true);
                //]]>
            </script>



    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
    </div>
    </div>
    </div>

