<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>

<!DOCTYPE html>

<!--[if lt IE 7 ]> <html lang="en" id="top" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" id="top" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" id="top" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" id="top" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" id="top" class="no-js"> <!--<![endif]-->

<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().' custom-background"':' custom-background' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div id="page" class="page full hfeed site">
        <?php echo $this->getChildHtml('header') ?>
        <div class="main-container col3-layout container">
            <div class="col-md-12">
                <div class="main">
                    <div class="main row">
                        <?php echo $this->getChildHtml('breadcrumbs') ?>
                    </div>
                    <div class="row col-main col-wrappe"  id="content">
                        <?php // This left_first block will display above the main content on smaller viewports ?>
                        <?php if ($_leftContent = $this->getChildHtml('left_first')): ?>
                            <div class="col-left sidebar col-left-first"><?php echo $_leftContent;   ?></div>
                        <?php endif; ?>
                        <div class="col-md-6 col-main">
                            <?php echo $this->getChildHtml('global_messages') ?>
                            <?php echo $this->getChildHtml('content') ?>
                        </div>
                        <div class="col-md-3 col-left sidebar"><?php echo $this->getChildHtml('left') ?></div>
                    </div>
                    <div class="col-md-3 col-right sidebar"><?php echo $this->getChildHtml('right') ?></div>
                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml('footer_before') ?>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
